require "file_utils"

module Lune
  module Runtime
    module Generator
      LUNEJS_DIR = "#{DEFAULT_FRONTEND_DIR}/#{LUNEJS_SUBDIR}"

      # ----------------------------
      # Runtime JS
      # ----------------------------
      def self.generate_runtime_js(bindings : Array(Lune::Binding)) : String
        stubs = bindings.map(&.to_js_stub).join("\n")

        <<-JS
        // Generated by Lune — do not edit by hand.

        export const __lune = {
          call(name, ...args) {
            return window[name](...args);
          },
        };

        export function on(name, cb)       { window.__lune_on(name, cb, -1); }
        export function once(name, cb)     { window.__lune_on(name, cb,  1); }
        export function off(name, cb)      { window.__lune_off(name, cb); }
        export function emit(name, data)   { return window.__lune_js_emit(name, data); }

        export function onFileDrop(cb) {
          window.__lune_on("fileDrop", function(data) { cb(data.x, data.y, data.paths); }, -1);
        }
        export function onFileDropOff() { window.__lune_off("fileDrop"); }

        #{stubs}
        JS
      end

      def self.generate_runtime_dts(bindings : Array(Lune::Binding)) : String
        sigs = bindings.map(&.to_dts_sig).join("\n")

        <<-DTS
        // Generated by Lune — do not edit by hand.

        export interface LuneEnvironment {
          os: "darwin" | "linux" | "windows";
          arch: string;
          debug: boolean;
        }

        export interface LuneError {
          code: string;
          error: string;
        }

        export interface ScreenInfo { width: number; height: number; scale: number; }

        export declare function on(name: string, cb: (data: unknown) => void): void;
        export declare function once(name: string, cb: (data: unknown) => void): void;
        export declare function off(name: string, cb?: (data: unknown) => void): void;
        export declare function emit(name: string, data?: unknown): Promise<void>;
        export declare function onFileDrop(cb: (x: number, y: number, paths: string[]) => void): void;
        export declare function onFileDropOff(): void;

        #{sigs}
        DTS
      end

      # ----------------------------
      # App JS
      # ----------------------------
      def self.generate_app_js(bindings : Array(Binding)) : String
        grouped = Hash(String, Array(Binding)).new { |h, k| h[k] = [] of Binding }

        bindings.each do |b|
          grouped[b.namespace] << b
        end

        stubs = String.build do |sb|
          grouped.each do |ns, bnds|
            parts = ns.split("::")
            head = parts.first

            sb << "export const #{head} = "
            sb << build_namespace(parts, bnds)
            sb << ";\n\n"
          end
        end

        <<-JS
        // Generated by Lune — do not edit by hand.
        // #{bindings.size} binding(s)

        import { __lune } from "../runtime/runtime.js";

        #{stubs}

        export const api = {
          #{grouped.keys.map { |ns| ns.split("::").first }.uniq.join(",\n")}
        };

        export default api;
        JS
      end

      # ----------------------------
      # Namespace builder
      # ----------------------------
      private def self.build_namespace(parts : Array(String), bindings : Array(Binding)) : String
        head = parts.first

        # ----------------------------
        # Leaf node → actual functions
        # ----------------------------
        if parts.size == 1
          return String.build do |s|
            s << "{\n"
            bindings.each { |b| s << b.to_js_stub << "\n" }
            s << "}"
          end
        end

        # ----------------------------
        # Parent namespace → nested object
        # ----------------------------
        child = parts[1]

        return String.build do |s|
          s << "{\n"
          s << "  #{child}: "
          s << build_namespace(parts[1..], bindings)
          s << "\n}"
        end
      end

      # ----------------------------
      # App DTS
      # ----------------------------
      def self.generate_app_dts(bindings : Array(Binding)) : String
        grouped = Hash(String, Array(Binding)).new { |h, k| h[k] = [] of Binding }

        bindings.each do |b|
          grouped[b.namespace] << b
        end

        interfaces = String.build do |sb|
          grouped.each do |ns, bnds|
            parts = ns.split("::")

            sb << build_dts_namespace(parts, bnds)
            sb << "\n"
          end
        end

        api_interface = String.build do |sb|
          sb << "export interface Api {\n"

          grouped.each do |ns, _|
            top = ns.split("::").first
            sb << "  #{top}: #{top};\n"
          end

          sb << "}\n"
        end

        <<-DTS
        // Generated by Lune — do not edit by hand.

        #{interfaces}

        #{api_interface}

        export declare const api: Api;

        export default api;
        DTS
      end

      private def self.build_dts_namespace(parts : Array(String), bindings : Array(Binding)) : String
        head = parts.first

        # ----------------------------
        # Leaf: real function signatures
        # ----------------------------
        if parts.size == 1
          return String.build do |s|
            s << "export interface #{head} {\n"
            bindings.each { |b| s << b.to_dts_sig << "\n" }
            s << "}\n"
          end
        end

        # ----------------------------
        # Parent: ONLY type references, NOT declarations
        # ----------------------------
        child = parts[1]

        return String.build do |s|
          s << "export interface #{head} {\n"
          s << "  #{child}: #{child};\n"
          s << "}\n\n"

          # IMPORTANT: emit child interface separately (not inside parent)
          s << build_dts_namespace(parts[1..], bindings)
        end
      end

      # ----------------------------
      # File writing
      # ----------------------------
      private def self.write_if_changed(path : String, content : String) : Bool
        return false if File.exists?(path) && File.read(path) == content
        File.write(path, content)
        true
      end

      def self.write_js(bindings : Array(Binding), lunejs_dir : String = LUNEJS_DIR)
        user_bindings    = bindings.reject(&.internal?)
        runtime_bindings = bindings.select(&.internal?)

        app_path         = File.join(lunejs_dir, "app", "App.js")
        app_dts_path     = File.join(lunejs_dir, "app", "App.d.ts")
        runtime_path     = File.join(lunejs_dir, "runtime", "runtime.js")
        runtime_dts_path = File.join(lunejs_dir, "runtime", "runtime.d.ts")

        FileUtils.mkdir_p(File.dirname(app_path))
        FileUtils.mkdir_p(File.dirname(runtime_path))

        runtime_changed = write_if_changed(runtime_path, generate_runtime_js(runtime_bindings))
        write_if_changed(runtime_dts_path, generate_runtime_dts(runtime_bindings))

        app_changed = write_if_changed(app_path, generate_app_js(user_bindings))
        write_if_changed(app_dts_path, generate_app_dts(user_bindings))

        if runtime_changed || app_changed
          Lune.logger.info { "Lune JS written → #{app_path}, #{runtime_path}" }
        end
      end

      def self.crystal_to_ts(type : String) : String
        case type
        when "String"                               then "string"
        when "Bool"                                 then "boolean"
        when "Nil"                                  then "void"
        when "Int32", "Int64", "Float32", "Float64" then "number"
        when "Array"                                then "any[]"
        when "Hash"                                 then "Record<string, any>"
        else                                             "Record<string, any>"
        end
      end
    end
  end
end
