require "file_utils"

module Lune
  module Runtime
    module Generator
      LUNEJS_DIR = "#{DEFAULT_FRONTEND_DIR}/#{LUNEJS_SUBDIR}"

      # ----------------------------
      # Runtime JS
      # ----------------------------
      def self.generate_runtime_js(bindings : Array(Lune::Binding), capabilities : Array(Lune::Capability) = [] of Lune::Capability) : String
        binding_groups, helper_groups, all_namespaces = namespace_groups(bindings, capabilities, &.js_helpers)

        namespace_blocks = all_namespaces.map do |ns|
          methods = String.build do |sb|
            binding_groups[ns]?.try &.each { |b| sb << b.to_js_stub << "\n" }
            sb << (helper_groups[ns]? || "")
          end
          "export const #{ns} = {\n#{methods}};"
        end.join("\n\n")

        runtime_members = all_namespaces.join(",\n  ")

        <<-JS
        // Generated by Lune — do not edit by hand.

        export class LuneError extends Error {
          constructor(code, message) {
            super(message);
            this.name = "LuneError";
            this.code = code;
          }
        }

        export const __lune = {
          call(name, ...args) {
            return window[name](...args).catch(function(err) {
              if (err !== null && typeof err === 'object' && typeof err.code === 'string') {
                throw new LuneError(err.code, err.error);
              }
              throw err;
            });
          },
        };

        #{namespace_blocks}

        export const runtime = {
          #{runtime_members}
        };

        export default runtime;
        JS
      end

      def self.generate_runtime_dts(bindings : Array(Lune::Binding), capabilities : Array(Lune::Capability) = [] of Lune::Capability) : String
        binding_groups, helper_groups, all_namespaces = namespace_groups(bindings, capabilities, &.dts_helpers)

        interfaces = all_namespaces.map do |ns|
          members = String.build do |sb|
            binding_groups[ns]?.try &.each { |b| sb << b.to_dts_sig << "\n" }
            sb << (helper_groups[ns]? || "")
          end
          "export interface #{ns} {\n#{members}}"
        end.join("\n\n")

        runtime_members = all_namespaces.map { |ns| "  #{ns}: #{ns};" }.join("\n")

        <<-DTS
        // Generated by Lune — do not edit by hand.

        export interface LuneEnvironment {
          os: "darwin" | "linux" | "windows";
          arch: string;
          debug: boolean;
        }

        export interface TrayMenuItem {
          id: string;
          label: string;
        }

        export interface ContextMenuItem {
          id?: string;
          label?: string;
          enabled?: boolean;
          separator?: boolean;
        }

        export declare class LuneError extends Error {
          readonly code: string;
          constructor(code: string, message: string);
        }

        export interface ScreenInfo { width: number; height: number; scale: number; }

        #{interfaces}

        export interface Runtime {
        #{runtime_members}
        }

        export declare const runtime: Runtime;
        export default runtime;
        DTS
      end

      # ----------------------------
      # Shared grouping
      # ----------------------------
      private def self.namespace_groups(
        bindings : Array(Lune::Binding),
        capabilities : Array(Lune::Capability),
        &helper_fn : Lune::Capability -> String
      ) : Tuple(Hash(String, Array(Lune::Binding)), Hash(String, String), Array(String))
        binding_groups = Hash(String, Array(Lune::Binding)).new { |h, k| h[k] = [] of Lune::Binding }
        bindings.each { |b| binding_groups[b.namespace] << b }

        helper_groups = Hash(String, String).new
        capabilities.each do |cap|
          h = helper_fn.call(cap)
          next if h.empty?
          helper_groups[cap.binding_namespace] = (helper_groups[cap.binding_namespace]? || "") + h
        end

        all_namespaces = (binding_groups.keys + helper_groups.keys).uniq
        {binding_groups, helper_groups, all_namespaces}
      end

      # ----------------------------
      # App JS
      # ----------------------------
      def self.generate_app_js(bindings : Array(Binding)) : String
        grouped = Hash(String, Array(Binding)).new { |h, k| h[k] = [] of Binding }

        bindings.each do |b|
          grouped[b.namespace] << b
        end

        stubs = String.build do |sb|
          grouped.each do |ns, bnds|
            parts = ns.split("::")
            head = parts.first

            sb << "export const #{head} = "
            sb << build_namespace(parts, bnds)
            sb << ";\n\n"
          end
        end

        <<-JS
        // Generated by Lune — do not edit by hand.
        // #{bindings.size} binding(s)

        import { __lune } from "../runtime/runtime.js";

        #{stubs}

        export const api = {
          #{grouped.keys.map { |ns| ns.split("::").first }.uniq.join(",\n")}
        };

        export default api;
        JS
      end

      # ----------------------------
      # Namespace builder
      # ----------------------------
      private def self.build_namespace(parts : Array(String), bindings : Array(Binding)) : String
        head = parts.first

        # ----------------------------
        # Leaf node → actual functions
        # ----------------------------
        if parts.size == 1
          return String.build do |s|
            s << "{\n"
            bindings.each { |b| s << b.to_js_stub << "\n" }
            s << "}"
          end
        end

        # ----------------------------
        # Parent namespace → nested object
        # ----------------------------
        child = parts[1]

        return String.build do |s|
          s << "{\n"
          s << "  #{child}: "
          s << build_namespace(parts[1..], bindings)
          s << "\n}"
        end
      end

      # ----------------------------
      # App DTS
      # ----------------------------
      def self.generate_app_dts(bindings : Array(Binding)) : String
        grouped = Hash(String, Array(Binding)).new { |h, k| h[k] = [] of Binding }

        bindings.each do |b|
          grouped[b.namespace] << b
        end

        interfaces = String.build do |sb|
          grouped.each do |ns, bnds|
            parts = ns.split("::")

            sb << build_dts_namespace(parts, bnds)
            sb << "\n"
          end
        end

        api_interface = String.build do |sb|
          sb << "export interface Api {\n"

          grouped.each do |ns, _|
            top = ns.split("::").first
            sb << "  #{top}: #{top};\n"
          end

          sb << "}\n"
        end

        <<-DTS
        // Generated by Lune — do not edit by hand.

        #{interfaces}

        #{api_interface}

        export declare const api: Api;

        export default api;
        DTS
      end

      private def self.build_dts_namespace(parts : Array(String), bindings : Array(Binding)) : String
        head = parts.first

        # ----------------------------
        # Leaf: real function signatures
        # ----------------------------
        if parts.size == 1
          return String.build do |s|
            s << "export interface #{head} {\n"
            bindings.each { |b| s << b.to_dts_sig << "\n" }
            s << "}\n"
          end
        end

        # ----------------------------
        # Parent: ONLY type references, NOT declarations
        # ----------------------------
        child = parts[1]

        return String.build do |s|
          s << "export interface #{head} {\n"
          s << "  #{child}: #{child};\n"
          s << "}\n\n"

          # IMPORTANT: emit child interface separately (not inside parent)
          s << build_dts_namespace(parts[1..], bindings)
        end
      end

      # ----------------------------
      # File writing
      # ----------------------------
      private def self.write_if_changed(path : String, content : String) : Bool
        return false if File.exists?(path) && File.read(path) == content
        File.write(path, content)
        true
      end

      def self.write_js(bindings : Array(Binding), lunejs_dir : String = LUNEJS_DIR, capabilities : Array(Lune::Capability) = [] of Lune::Capability) : Nil
        user_bindings = bindings.reject(&.internal?)
        runtime_bindings = bindings.select(&.internal?)

        app_path = File.join(lunejs_dir, "app", "App.js")
        app_dts_path = File.join(lunejs_dir, "app", "App.d.ts")
        runtime_path = File.join(lunejs_dir, "runtime", "runtime.js")
        runtime_dts_path = File.join(lunejs_dir, "runtime", "runtime.d.ts")

        FileUtils.mkdir_p(File.dirname(app_path))
        FileUtils.mkdir_p(File.dirname(runtime_path))

        runtime_changed = write_if_changed(runtime_path, generate_runtime_js(runtime_bindings, capabilities))
        write_if_changed(runtime_dts_path, generate_runtime_dts(runtime_bindings, capabilities))

        app_changed = write_if_changed(app_path, generate_app_js(user_bindings))
        write_if_changed(app_dts_path, generate_app_dts(user_bindings))

        if runtime_changed || app_changed
          Lune.logger.info { "Lune JS written → #{app_path}, #{runtime_path}" }
        end
      end

      def self.crystal_to_ts(type : String) : String
        case type
        when "String"                               then "string"
        when "Bool"                                 then "boolean"
        when "Nil"                                  then "void"
        when "Int32", "Int64", "Float32", "Float64" then "number"
        when "Array"                                then "any[]"
        when "Hash"                                 then "Record<string, any>"
        else                                             "Record<string, any>"
        end
      end
    end
  end
end
