// Generated by Lune — do not edit by hand.
// 5 binding(s)

import { __lune } from "../runtime/runtime.js";

export const Demo = {
  greet(args) {
    return __lune.call("Demo.greet", args);
  },
  reverse(args) {
    return __lune.call("Demo.reverse", args);
  },
  fileInfo(args) {
    return __lune.call("Demo.fileInfo", args);
  },
  failWith(args) {
    return __lune.call("Demo.failWith", args);
  },
  processFiles(args) {
    return __lune.call("Demo.processFiles", args);
  },
};

export const api = { Demo };
export default api;