require "file_utils"
require "vow/codegen/type_map"
require "vow/manifest"

module Lune
  module Generator
    # Builds the `Vow::Manifest` for a set of bindings — the static contract
    # behind the generated client (and, later, the dispatch registry and an
    # introspection endpoint). Each binding becomes one `ProcedureDescriptor`
    # named by its wire `id`; *types* are the captured surface types (deduped by
    # Crystal name) the signatures reference.
    def self.manifest(bindings : Array(Binding), types : Array(Vow::TypeDescriptor) = [] of Vow::TypeDescriptor) : Vow::Manifest
      Vow::Manifest.new(bindings.map(&.to_vow_descriptor), types.uniq(&.crystal_name))
    end

    # Maps captured surface types to the `known`-types lookup the TS mapper uses:
    # a type's full Crystal name AND its basename both resolve to the generated
    # interface name, so a signature written qualified or unqualified resolves.
    def self.known_types(types : Array(Vow::TypeDescriptor)) : Hash(String, String)
      known = {} of String => String
      types.each do |t|
        known[t.crystal_name] = t.name
        known[t.name] = t.name
      end
      known
    end

    # Nested-hash namespace tree. Keys are `::`-split segments of the binding
    # namespace; leaves are arrays of pre-rendered string fragments (binding
    # stubs and plugin helpers concatenated in order). Recursive alias mirrors
    # `Lune::Plugins::Tray` → tree["Lune"]["Plugins"]["Tray"] = [stubs…].
    private alias NsTree = Hash(String, NsTree) | Array(String)

    # Built-ins land under `Lune::Plugins::*`; when at least one is active we
    # emit a `lune` named export aliased to `Lune.Plugins` so user code can
    # write `lune.Tray.show()` instead of `Lune.Plugins.Tray.show()`. Skip
    # the alias when the tree has no `Lune.Plugins` subtree (a build with
    # every built-in disabled) — `lune = Lune.Plugins` would throw at module
    # load.
    private def self.plugins_alias_available?(tree : Hash(String, NsTree)) : Bool
      lune = tree["Lune"]?
      lune.is_a?(Hash) && lune.has_key?("Plugins")
    end

    # ----------------------------
    # Runtime JS / DTS
    # ----------------------------
    def self.generate_runtime_js(
      bindings : Array(Lune::Binding),
      plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
      unavailable_plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
    ) : String
      tree = build_tree(bindings, plugins, unavailable_plugins,
        helper_fn: ->(p : Lune::Plugin) { p.js_helpers },
        unavailable_fn: ->(p : Lune::Plugin) { p.unavailable_js_stub(Lune::Plugins::CURRENT_PLATFORM) })
      hash = tree.as(Hash)
      blocks = hash.map { |top, sub| "export const #{top} = #{render_js(sub)};" }
      blocks << "export const lune = Lune.Plugins;" if plugins_alias_available?(hash)

      <<-JS
        // Generated by Lune — do not edit by hand.

        #{Lune::Error.js_stub}

        #{Lune::Binding.js_runtime}

        #{blocks.join("\n\n")}
        JS
    end

    def self.generate_runtime_dts(
      bindings : Array(Lune::Binding),
      plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
      unavailable_plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
      known : Hash(String, String) = {} of String => String,
      types : Array(Vow::TypeDescriptor) = [] of Vow::TypeDescriptor,
    ) : String
      tree = build_tree(bindings, plugins, unavailable_plugins, dts: true, known: known,
        helper_fn: ->(p : Lune::Plugin) { p.dts_helpers },
        unavailable_fn: ->(p : Lune::Plugin) { p.unavailable_dts_stub })
      hash = tree.as(Hash)
      decls = hash.map { |top, sub| "export declare const #{top}: #{render_dts(sub)};" }
      decls << "export declare const lune: typeof Lune.Plugins;" if plugins_alias_available?(hash)

      ts_type_block = render_interfaces(types, known)

      <<-DTS
        // Generated by Lune — do not edit by hand.

        #{Lune::Error.dts_stub}
        #{ts_type_block}
        #{decls.join("\n\n")}
        DTS
    end

    # Renders one `export interface` per captured surface type, in capture order,
    # mapping each field type through the `known`-aware TS mapper. Returns "" for
    # an empty set so the heredoc collapses cleanly (no orphan blank line). The
    # field name is the wire key already resolved by capture (honoring
    # `@[JSON::Field(key:)]`), quoted when it isn't a valid JS identifier.
    private def self.render_interfaces(types : Array(Vow::TypeDescriptor), known : Hash(String, String)) : String
      return "" if types.empty?
      blocks = types.map do |t|
        body = t.fields.map { |f| "  #{ts_member(f.name)}: #{crystal_to_ts(f.type, known)};" }.join("\n")
        "export interface #{t.name} {\n#{body}\n}"
      end
      "\n#{blocks.join("\n\n")}\n"
    end

    private def self.ts_member(name : String) : String
      name.matches?(/\A[A-Za-z_$][A-Za-z0-9_$]*\z/) ? name : name.inspect
    end

    # ----------------------------
    # App JS / DTS — same shape as runtime, just no LuneError/__lune
    # declarations and an import of `__lune` from the runtime file.
    # ----------------------------
    def self.generate_app_js(bindings : Array(Binding)) : String
      empty = [] of Lune::Plugin
      tree = build_tree(bindings, empty, empty,
        helper_fn: ->(p : Lune::Plugin) { p.js_helpers },
        unavailable_fn: ->(p : Lune::Plugin) { nil.as(String?) })
      hash = tree.as(Hash)
      blocks = hash.map { |top, sub| "export const #{top} = #{render_js(sub)};" }
      api_members = hash.keys.join(", ")

      <<-JS
        // Generated by Lune — do not edit by hand.
        // #{bindings.size} binding(s)

        import { __lune } from "../runtime/runtime.js";

        #{blocks.join("\n\n")}

        export const api = { #{api_members} };
        export default api;
        JS
    end

    def self.generate_app_dts(
      bindings : Array(Binding),
      known : Hash(String, String) = {} of String => String,
      types : Array(Vow::TypeDescriptor) = [] of Vow::TypeDescriptor,
    ) : String
      empty = [] of Lune::Plugin
      tree = build_tree(bindings, empty, empty, dts: true, known: known,
        helper_fn: ->(p : Lune::Plugin) { p.dts_helpers },
        unavailable_fn: ->(p : Lune::Plugin) { nil.as(String?) })
      hash = tree.as(Hash)
      decls = hash.map { |top, sub| "export declare const #{top}: #{render_dts(sub)};" }
      api_body = hash.map { |top, sub| "  #{top}: #{render_dts(sub)};" }.join("\n")

      ts_type_block = render_interfaces(types, known)

      <<-DTS
        // Generated by Lune — do not edit by hand.
        #{ts_type_block}
        #{decls.join("\n\n")}

        export declare const api: {
        #{api_body}
        };

        export default api;
        DTS
    end

    # ----------------------------
    # Tree building
    # ----------------------------
    # Walks the bindings + plugin helpers + unavailable stubs, splits each
    # `binding_namespace` by `::`, and inserts the rendered string fragment(s)
    # at the leaf of the nested Hash. Helpers and bindings merge into the
    # same leaf array; the unavailable_*_stub plugins land in their own leaf
    # only if no live binding/helper already claimed that path.
    private def self.build_tree(
      bindings : Array(Lune::Binding),
      plugins : Array(Lune::Plugin),
      unavailable : Array(Lune::Plugin),
      helper_fn : Lune::Plugin -> String,
      unavailable_fn : Lune::Plugin -> String?,
      dts : Bool = false,
      known : Hash(String, String) = {} of String => String,
    ) : NsTree
      stub_fn = ->(b : Lune::Binding) { dts ? b.to_dts_sig(known) + "\n" : b.to_js_stub + "\n" }

      root = {} of String => NsTree
      live = Set(String).new

      bindings.group_by(&.namespace).each do |ns, bnds|
        live << ns
        insert(root, ns.split("::"), bnds.map { |b| stub_fn.call(b) })
      end

      plugins.each do |p|
        h = helper_fn.call(p)
        next if h.empty?
        live << p.binding_namespace
        insert(root, p.binding_namespace.split("::"), [h])
      end

      unavailable.each do |p|
        next if live.includes?(p.binding_namespace)
        body = unavailable_fn.call(p)
        next unless body
        insert(root, p.binding_namespace.split("::"), [body])
      end

      root
    end

    private def self.insert(tree : Hash(String, NsTree), path : Array(String), entries : Array(String)) : Nil
      head, *rest = path
      if rest.empty?
        existing = tree[head]?
        if existing.is_a?(Array)
          existing.concat(entries)
        else
          tree[head] = entries
        end
        return
      end

      child = tree[head]?
      unless child.is_a?(Hash)
        child = {} of String => NsTree
        tree[head] = child
      end
      insert(child, rest, entries)
    end

    # ----------------------------
    # Rendering — leaves are object bodies, branches are nested objects.
    # ----------------------------
    private def self.render_js(node : NsTree) : String
      case node
      in Array(String)
        String.build do |s|
          s << "{\n"
          node.each { |frag| s << frag }
          s << "}"
        end
      in Hash
        String.build do |s|
          s << "{\n"
          node.each { |k, v| s << "  #{k}: " << render_js(v) << ",\n" }
          s << "}"
        end
      end
    end

    private def self.render_dts(node : NsTree) : String
      case node
      in Array(String)
        String.build do |s|
          s << "{\n"
          node.each { |frag| s << frag }
          s << "}"
        end
      in Hash
        String.build do |s|
          s << "{\n"
          node.each { |k, v| s << "  #{k}: " << render_dts(v) << ";\n" }
          s << "}"
        end
      end
    end

    # ----------------------------
    # File writing
    # ----------------------------
    private def self.write_if_changed(path : String, content : String) : Bool
      return false if File.exists?(path) && File.read(path) == content
      File.write(path, content)
      true
    end

    def self.write_js(
      bindings : Array(Binding),
      lunejs_dir : String,
      plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
      unavailable_plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
      plugin_types : Array(Vow::TypeDescriptor) = [] of Vow::TypeDescriptor,
      user_types : Array(Vow::TypeDescriptor) = [] of Vow::TypeDescriptor,
    ) : Nil
      user_bindings = bindings.reject(&.internal?)
      runtime_bindings = bindings.select(&.internal?)

      # `known` spans every captured type so a signature in either file resolves
      # a struct reference; interfaces are emitted per file (plugin types →
      # runtime.d.ts, user types → App.d.ts) so neither file double-declares.
      known = known_types(plugin_types + user_types)
      runtime_types = plugin_types.uniq(&.crystal_name)
      app_types = user_types.uniq(&.crystal_name)

      app_path = File.join(lunejs_dir, "app", "App.js")
      app_dts_path = File.join(lunejs_dir, "app", "App.d.ts")
      runtime_path = File.join(lunejs_dir, "runtime", "runtime.js")
      runtime_dts_path = File.join(lunejs_dir, "runtime", "runtime.d.ts")

      FileUtils.mkdir_p(File.dirname(app_path))
      FileUtils.mkdir_p(File.dirname(runtime_path))

      runtime_changed = write_if_changed(runtime_path, generate_runtime_js(runtime_bindings, plugins, unavailable_plugins))
      write_if_changed(runtime_dts_path, generate_runtime_dts(runtime_bindings, plugins, unavailable_plugins, known, runtime_types))

      app_changed = write_if_changed(app_path, generate_app_js(user_bindings))
      write_if_changed(app_dts_path, generate_app_dts(user_bindings, known, app_types))

      if runtime_changed || app_changed
        Lune.logger.info { "Lune JS written → #{app_path}, #{runtime_path}" }
      end
    end

    # TypeScript type mapping is delegated to vow's strict mapper. In *argument*
    # position `Vow::Codegen.crystal_to_ts` handles primitives, generics
    # (`Array`/`Hash`/`Tuple`/`NamedTuple`/`Set`), unions, and `JSON::Any`, and
    # raises `Vow::Codegen::UnmappableType` on anything it can't map honestly
    # rather than silently widening it to `Record<string, any>`. The captured-
    # types map is empty here; Phase 1 threads the manifest through so struct
    # references resolve to their generated interface names.
    def self.crystal_to_ts(type : String, known : Hash(String, String) = {} of String => String) : String
      Vow::Codegen.crystal_to_ts(type, known)
    end

    # As `crystal_to_ts`, but for *return* position, where `Nil` maps to `void`
    # (`Promise<void>`) rather than `null`.
    def self.crystal_return_to_ts(type : String, known : Hash(String, String) = {} of String => String) : String
      Vow::Codegen.return_to_ts(type, known)
    end
  end
end
