require "file_utils"

module Lune
  module Generator
    # Nested-hash namespace tree. Keys are `::`-split segments of the binding
    # namespace; leaves are arrays of pre-rendered string fragments (binding
    # stubs and plugin helpers concatenated in order). Recursive alias mirrors
    # `Lune::Plugins::Tray` → tree["Lune"]["Plugins"]["Tray"] = [stubs…].
    private alias NsTree = Hash(String, NsTree) | Array(String)

    # Built-ins land under `Lune::Plugins::*`; when at least one is active we
    # emit a `lune` named export aliased to `Lune.Plugins` so user code can
    # write `lune.Tray.show()` instead of `Lune.Plugins.Tray.show()`. Skip
    # the alias when the tree has no `Lune.Plugins` subtree (a build with
    # every built-in disabled) — `lune = Lune.Plugins` would throw at module
    # load.
    private def self.plugins_alias_available?(tree : Hash(String, NsTree)) : Bool
      lune = tree["Lune"]?
      lune.is_a?(Hash) && lune.has_key?("Plugins")
    end

    # ----------------------------
    # Runtime JS / DTS
    # ----------------------------
    def self.generate_runtime_js(
      bindings : Array(Lune::Binding),
      plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
      unavailable_plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
    ) : String
      tree = build_tree(bindings, plugins, unavailable_plugins,
        helper_fn: ->(p : Lune::Plugin) { p.js_helpers },
        unavailable_fn: ->(p : Lune::Plugin) { p.unavailable_js_stub(Lune::Plugins::CURRENT_PLATFORM) })
      hash = tree.as(Hash)
      blocks = hash.map { |top, sub| "export const #{top} = #{render_js(sub)};" }
      blocks << "export const lune = Lune.Plugins;" if plugins_alias_available?(hash)

      <<-JS
        // Generated by Lune — do not edit by hand.

        export class LuneError extends Error {
          constructor(code, message) {
            super(message);
            this.name = "LuneError";
            this.code = code;
          }
        }

        export const __lune = {
          call(name, ...args) {
            return window[name](...args).catch(function(err) {
              if (err !== null && typeof err === 'object' && typeof err.code === 'string') {
                throw new LuneError(err.code, err.error);
              }
              throw err;
            });
          },
        };

        #{blocks.join("\n\n")}
        JS
    end

    def self.generate_runtime_dts(
      bindings : Array(Lune::Binding),
      plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
      unavailable_plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
    ) : String
      tree = build_tree(bindings, plugins, unavailable_plugins, dts: true,
        helper_fn: ->(p : Lune::Plugin) { p.dts_helpers },
        unavailable_fn: ->(p : Lune::Plugin) { p.unavailable_dts_stub })
      hash = tree.as(Hash)
      decls = hash.map { |top, sub| "export declare const #{top}: #{render_dts(sub)};" }
      decls << "export declare const lune: typeof Lune.Plugins;" if plugins_alias_available?(hash)

      <<-DTS
        // Generated by Lune — do not edit by hand.

        export declare class LuneError extends Error {
          readonly code: string;
          constructor(code: string, message: string);
        }

        #{decls.join("\n\n")}
        DTS
    end

    # ----------------------------
    # App JS / DTS — same shape as runtime, just no LuneError/__lune
    # declarations and an import of `__lune` from the runtime file.
    # ----------------------------
    def self.generate_app_js(bindings : Array(Binding)) : String
      empty = [] of Lune::Plugin
      tree = build_tree(bindings, empty, empty,
        helper_fn: ->(p : Lune::Plugin) { p.js_helpers },
        unavailable_fn: ->(p : Lune::Plugin) { nil.as(String?) })
      hash = tree.as(Hash)
      blocks = hash.map { |top, sub| "export const #{top} = #{render_js(sub)};" }
      api_members = hash.keys.join(", ")

      <<-JS
        // Generated by Lune — do not edit by hand.
        // #{bindings.size} binding(s)

        import { __lune } from "../runtime/runtime.js";

        #{blocks.join("\n\n")}

        export const api = { #{api_members} };
        export default api;
        JS
    end

    def self.generate_app_dts(bindings : Array(Binding)) : String
      empty = [] of Lune::Plugin
      tree = build_tree(bindings, empty, empty, dts: true,
        helper_fn: ->(p : Lune::Plugin) { p.dts_helpers },
        unavailable_fn: ->(p : Lune::Plugin) { nil.as(String?) })
      hash = tree.as(Hash)
      decls = hash.map { |top, sub| "export declare const #{top}: #{render_dts(sub)};" }
      api_body = hash.map { |top, sub| "  #{top}: #{render_dts(sub)};" }.join("\n")

      <<-DTS
        // Generated by Lune — do not edit by hand.

        #{decls.join("\n\n")}

        export declare const api: {
        #{api_body}
        };

        export default api;
        DTS
    end

    # ----------------------------
    # Tree building
    # ----------------------------
    # Walks the bindings + plugin helpers + unavailable stubs, splits each
    # `binding_namespace` by `::`, and inserts the rendered string fragment(s)
    # at the leaf of the nested Hash. Helpers and bindings merge into the
    # same leaf array; the unavailable_*_stub plugins land in their own leaf
    # only if no live binding/helper already claimed that path.
    private def self.build_tree(
      bindings : Array(Lune::Binding),
      plugins : Array(Lune::Plugin),
      unavailable : Array(Lune::Plugin),
      helper_fn : Lune::Plugin -> String,
      unavailable_fn : Lune::Plugin -> String?,
      dts : Bool = false,
    ) : NsTree
      stub_fn = ->(b : Lune::Binding) { dts ? b.to_dts_sig + "\n" : b.to_js_stub + "\n" }

      root = {} of String => NsTree
      live = Set(String).new

      bindings.group_by(&.namespace).each do |ns, bnds|
        live << ns
        insert(root, ns.split("::"), bnds.map { |b| stub_fn.call(b) })
      end

      plugins.each do |p|
        h = helper_fn.call(p)
        next if h.empty?
        live << p.binding_namespace
        insert(root, p.binding_namespace.split("::"), [h])
      end

      unavailable.each do |p|
        next if live.includes?(p.binding_namespace)
        body = unavailable_fn.call(p)
        next unless body
        insert(root, p.binding_namespace.split("::"), [body])
      end

      root
    end

    private def self.insert(tree : Hash(String, NsTree), path : Array(String), entries : Array(String)) : Nil
      head, *rest = path
      if rest.empty?
        existing = tree[head]?
        if existing.is_a?(Array)
          existing.concat(entries)
        else
          tree[head] = entries
        end
        return
      end

      child = tree[head]?
      unless child.is_a?(Hash)
        child = {} of String => NsTree
        tree[head] = child
      end
      insert(child, rest, entries)
    end

    # ----------------------------
    # Rendering — leaves are object bodies, branches are nested objects.
    # ----------------------------
    private def self.render_js(node : NsTree) : String
      case node
      in Array(String)
        String.build do |s|
          s << "{\n"
          node.each { |frag| s << frag }
          s << "}"
        end
      in Hash
        String.build do |s|
          s << "{\n"
          node.each { |k, v| s << "  #{k}: " << render_js(v) << ",\n" }
          s << "}"
        end
      end
    end

    private def self.render_dts(node : NsTree) : String
      case node
      in Array(String)
        String.build do |s|
          s << "{\n"
          node.each { |frag| s << frag }
          s << "}"
        end
      in Hash
        String.build do |s|
          s << "{\n"
          node.each { |k, v| s << "  #{k}: " << render_dts(v) << ";\n" }
          s << "}"
        end
      end
    end

    # ----------------------------
    # File writing
    # ----------------------------
    private def self.write_if_changed(path : String, content : String) : Bool
      return false if File.exists?(path) && File.read(path) == content
      File.write(path, content)
      true
    end

    def self.write_js(
      bindings : Array(Binding),
      lunejs_dir : String,
      plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
      unavailable_plugins : Array(Lune::Plugin) = [] of Lune::Plugin,
    ) : Nil
      user_bindings = bindings.reject(&.internal?)
      runtime_bindings = bindings.select(&.internal?)

      app_path = File.join(lunejs_dir, "app", "App.js")
      app_dts_path = File.join(lunejs_dir, "app", "App.d.ts")
      runtime_path = File.join(lunejs_dir, "runtime", "runtime.js")
      runtime_dts_path = File.join(lunejs_dir, "runtime", "runtime.d.ts")

      FileUtils.mkdir_p(File.dirname(app_path))
      FileUtils.mkdir_p(File.dirname(runtime_path))

      runtime_changed = write_if_changed(runtime_path, generate_runtime_js(runtime_bindings, plugins, unavailable_plugins))
      write_if_changed(runtime_dts_path, generate_runtime_dts(runtime_bindings, plugins, unavailable_plugins))

      app_changed = write_if_changed(app_path, generate_app_js(user_bindings))
      write_if_changed(app_dts_path, generate_app_dts(user_bindings))

      if runtime_changed || app_changed
        Lune.logger.info { "Lune JS written → #{app_path}, #{runtime_path}" }
      end
    end

    # Maps a Crystal-side type literal (as written in `args:` / `return_type:`)
    # to a TypeScript type. Handles parameterized generics recursively:
    #
    #   "Array(String)"                                  → "string[]"
    #   "Hash(String, Int32)"                            → "Record<string, number>"
    #   "Tuple(String, Int32)"                           → "[string, number]"
    #   "NamedTuple(width: Int32, height: Int32)"        → "{ width: number; height: number }"
    #   "Array(Hash(String, Bool))"                      → "Record<string, boolean>[]"
    #
    # Bare collection names (no params) fall back to `any[]` / `Record<string, any>`.
    # Unknown identifiers fall back to `Record<string, any>` for back-compat with
    # JSON::Serializable struct args.
    def self.crystal_to_ts(type : String) : String
      type = type.strip

      if inner = extract_generic(type, "Array")
        return "#{crystal_to_ts(inner)}[]"
      end
      if inner = extract_generic(type, "Hash")
        parts = split_top_level_args(inner)
        return parts.size == 2 ? "Record<#{crystal_to_ts(parts[0])}, #{crystal_to_ts(parts[1])}>" : "Record<string, any>"
      end
      if inner = extract_generic(type, "Tuple")
        return "[#{split_top_level_args(inner).map { |p| crystal_to_ts(p) }.join(", ")}]"
      end
      if inner = extract_generic(type, "NamedTuple")
        fields = split_top_level_args(inner).map do |pair|
          name, rest = pair.split(":", 2)
          "#{name.strip}: #{crystal_to_ts(rest.strip)}"
        end
        return "{ #{fields.join("; ")} }"
      end

      case type
      when "String"                                                                                       then "string"
      when "Bool"                                                                                         then "boolean"
      when "Nil"                                                                                          then "void"
      when "Int8", "Int16", "Int32", "Int64", "UInt8", "UInt16", "UInt32", "UInt64", "Float32", "Float64" then "number"
      when "Array"                                                                                        then "any[]"
      when "Hash"                                                                                         then "Record<string, any>"
      else                                                                                                     "Record<string, any>"
      end
    end

    # Returns the inner type string between parens for `Name(inner)`, or nil
    # if `type` is not a parameterized form of `name`.
    private def self.extract_generic(type : String, name : String) : String?
      prefix = "#{name}("
      return nil unless type.starts_with?(prefix) && type.ends_with?(')')
      type[prefix.size..-2]
    end

    # Splits a comma-separated argument list at top level, ignoring commas
    # inside nested parens. `"String, Hash(String, Int32)"` → `["String", "Hash(String, Int32)"]`.
    private def self.split_top_level_args(s : String) : Array(String)
      parts = [] of String
      depth = 0
      start = 0
      s.each_char_with_index do |c, i|
        case c
        when '(' then depth += 1
        when ')' then depth -= 1
        when ','
          if depth == 0
            parts << s[start...i].strip
            start = i + 1
          end
        end
      end
      parts << s[start..].strip
      parts
    end
  end
end
