require "file_utils"

module Lune
  module Runtime
    LUNEJS_DIR = "frontend/lunejs"

    def self.generate_runtime_js : String
      <<-JS
      // Generated by Lune — do not edit by hand.

      export const __lune = {
        call(name, ...args) {
          return window[name](...args);
        },
      };

      // Event bus — wraps the globals set up by Lune's wv.init script.
      export function on(name, cb)   { window.__lune_on(name, cb, -1); }
      export function once(name, cb) { window.__lune_on(name, cb,  1); }
      export function off(name, cb)  { window.__lune_off(name, cb); }

      // Runtime functions — backed by built-in Crystal bindings.
      export function quit()          { return __lune.call("__lune.quit"); }
      export function openURL(url)    { return __lune.call("__lune.openURL", url); }
      export function environment()   { return __lune.call("__lune.environment"); }
      JS
    end

    def self.generate_runtime_dts : String
      <<-DTS
      // Generated by Lune — do not edit by hand.

      export interface LuneEnvironment {
        os: "darwin" | "linux" | "windows";
        arch: string;
        debug: boolean;
      }

      export declare function on(name: string, cb: (data: unknown) => void): void;
      export declare function once(name: string, cb: (data: unknown) => void): void;
      export declare function off(name: string, cb?: (data: unknown) => void): void;

      export declare function quit(): Promise<void>;
      export declare function openURL(url: string): Promise<void>;
      export declare function environment(): Promise<LuneEnvironment>;
      DTS
    end

    def self.generate_app_dts(binding_names : Array(String)) : String
      stubs = String.build do |sb|
        binding_names.each do |name|
          safe = name.gsub(".", "__").gsub(/[^A-Za-z0-9_]/, "_")
          sb << "export declare function #{safe}(...args: unknown[]): Promise<unknown>;\n"
        end
      end

      <<-DTS
      // Generated by Lune — do not edit by hand.
      // #{binding_names.size} binding(s): #{binding_names.join(", ")}

      #{stubs}
      export declare const api: Record<string, (...args: unknown[]) => Promise<unknown>>;
      export default api;
      DTS
    end

    def self.generate_app_js(binding_names : Array(String)) : String
      stubs = String.build do |sb|
        binding_names.each do |name|
          safe = name.gsub(".", "__").gsub(/[^A-Za-z0-9_]/, "_")
          sb << "export function #{safe}(...args) { return __lune.call(#{name.inspect}, ...args); }\n"
        end
      end

      <<-JS
      // Generated by Lune — do not edit by hand.
      // #{binding_names.size} binding(s): #{binding_names.join(", ")}

      import { __lune } from "../runtime/runtime.js";

      // Named stubs — import these directly for IDE autocompletion:
      #{stubs}

      // Dynamic api proxy — routes api.foo(...) and api.ns.bar(...) to the
      // webview-injected globals without requiring binding names at build time.
      function __makeApi(prefix) {
        return new Proxy(function () {}, {
          apply(_, __, args) {
            return __lune.call(prefix, ...args);
          },
          get(_, prop) {
            if (typeof prop !== "string") return undefined;
            const name = prefix ? prefix + "." + prop : prop;
            return __makeApi(name);
          },
        });
      }

      export const api = __makeApi("");
      export default api;
      JS
    end

    private def self.write_if_changed(path : String, content : String) : Bool
      return false if File.exists?(path) && File.read(path) == content
      File.write(path, content)
      true
    end

    def self.write_js(binding_names : Array(String), lunejs_dir : String = LUNEJS_DIR)
      app_path = File.join(lunejs_dir, "app", "App.js")
      app_dts_path = File.join(lunejs_dir, "app", "App.d.ts")
      runtime_path = File.join(lunejs_dir, "runtime", "runtime.js")
      runtime_dts_path = File.join(lunejs_dir, "runtime", "runtime.d.ts")

      FileUtils.mkdir_p(File.dirname(app_path))
      FileUtils.mkdir_p(File.dirname(runtime_path))

      runtime_changed = write_if_changed(runtime_path, generate_runtime_js)
      write_if_changed(runtime_dts_path, generate_runtime_dts)
      app_changed = write_if_changed(app_path, generate_app_js(binding_names))
      write_if_changed(app_dts_path, generate_app_dts(binding_names))

      if runtime_changed || app_changed
        Lune.logger.info { "Lune JS written → #{app_path}, #{runtime_path}" }
      end
    end
  end
end
